Added logic for game finalization
StarkThink/starktrip-contracts pull request #24
Opened 2024-06-21 23:12 UTC by jbmkahdeksan

2024-06-21 23:51 UTC, Jonatan-Chaverri requested changes

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +        fn generate_leaderboard() -> LeaderBoard {
You need to use self: @ContractState as the first argument in order to be able to use this as self.generate_leaderboard

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            LeaderBoard {
You should validate first if the leaderboard is already set in the blockchain before creating a new one. Otherwise you will be creating a new leaderboard with every new game, losing data for all other players who played before.

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            LeaderBoard {
We just need to create the leaderboard once

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +        fn generate_leaderboard_player(id: u32, player_name: felt252, score: u32) -> LeaderBoard {
Same here, you are missing the first parameter. Also it is not required to have this "generate" functions if you will not do any logic inside them, you can just move the struct declaration directly into the move function or wherever you are calling it.

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +        fn create_round(world: IWorldDispatcher, game_id: u32) {
These two functions should be part of the "GameImpl" trait, not the "InternalTrait". And you should also add them in the dojo interface that is in this same contract.

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            let owner = get_caller_address();
This declaration is not doing anything.

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            store.set_spaceship(spaceship);
Some things missing from here
- Store the board
- Update the game model with the new round and store it.
- Emit the `GameEvent` with the updated values for round and score.

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +        fn end_game(game_id: u32) {
Things to do here 
- Store the game after update
- Store the leader board after update
- Store the leaderBoardPlayer
- Emit GameOver event.

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            if game.active {
change this for
`assert(game.active, 'game is not active')`

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +                    let GameOverEvent = GameOver { game_id: game_id, player_address: get_caller_address() };
Move this event to end_game()
also make sure that nothing else will be executed from here. You can try to return ()

2024-06-21 23:51 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +                    self.create_round(game_id);
Make sure not to execute anything else after this is executed.

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +            LeaderBoard {
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +        fn generate_leaderboard_player(id: u32, player_name: felt252, score: u32) -> LeaderBoard {
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +        fn create_round(world: IWorldDispatcher, game_id: u32) {
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +            let owner = get_caller_address();
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +            store.set_spaceship(spaceship);
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +        fn end_game(game_id: u32) {
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +            if game.active {
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +                    let GameOverEvent = GameOver { game_id: game_id, player_address: get_caller_address() };
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +                    let GameOverEvent = GameOver { game_id: game_id, player_address: get_caller_address() };
comment addressed

2024-06-22 00:28 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +                    self.create_round(game_id);
comment addressed

2024-06-22 00:44 UTC, Jonatan-Chaverri requested changes

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +    fn create_round(world: IWorldDispatcher, gmae_id: u32);
remove world from here, is not needed

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            assert!(game.active, "Game is not active");
remove the `!` its just `assert`, sorry if I send the wrong suggestion. Also, second argument should be a felt252 not string. Please make sure to build the project to make sure that everything is fine.

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +                self.end_game(game_id, world);
this args are inverted.

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +                self.create_round(world, game_id, get_caller_address());
don't call this from here. We will call it from UI once we receive the gameWinEvent.

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +                game_id: game_id, player_address: owner
what is owner? Please build the project first and solve issues there.

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +        fn create_round(world: IWorldDispatcher, game_id: u32, player_address: ContractAddress) {
This shouldn't take player_address as argument. You can get the address by either using get_caller_address() or retrieving game owner from game model.

2024-06-22 00:44 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            let new_player = LeaderBoardPlayers::new{ id: game.owner, player_name: game.player_name, score: game.score };
id here should be `leader_board.len_players`. Then update `leader_board.len_players += 1` (update should happen after). We should always insert new players at the end of the list. The id is the index of that list.

2024-06-22 00:45 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +        fn generate_leaderboard_player(id: u32, player_name: felt252, score: u32) -> LeaderBoard {
Remove empty function

2024-06-22 00:46 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            let mut leader_board: Game = store.get_leader_board(game_id);
leader_board id is always 1

2024-06-22 03:46 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +    fn create_round(world: IWorldDispatcher, gmae_id: u32);
how do we emit the event, then?

2024-06-22 03:47 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +    fn create_round(world: IWorldDispatcher, gmae_id: u32);
should I pass store as an argument?

2024-06-22 04:44 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +    fn create_round(world: IWorldDispatcher, gmae_id: u32);
understood and applied

2024-06-22 04:45 UTC, jbmkahdeksan commented on src/systems/game_system.cairo
> +                self.end_game(game_id, world);
solved

2024-06-22 04:55 UTC, Jonatan-Chaverri commented on src/systems/game_system.cairo
> +            let CreateGameEvent = CreateGame {
You have to emit a GameEvent and also update the game entity.

2024-06-22 05:10 UTC, merged